default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  port: 5430
  password: sa
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: testTask

test:
  <<: *default
  database: testDB

production:
  <<: *default
  database: testTask
